floating_ips_client => compute_floating_ips_client
Since commit 74890acee32b1 in tempest tempest/scenario/manager.py
tempest.scenario.test_numa_topology.TestServerNumaTopo started to fail.
>>
File "tempest/scenario/test_numa_topology.py", line 111, in verify_ssh
    floating_ip = self.floating_ips_client.create_floating_ip()[
AttributeError:
'TestServerNumaTopo' object has no attribute 'floating_ips_client'
>>

This commit should fix that.

Change-Id: I5d38b7d9962cb14ae502906ffba2611bd2882a66