Fixed getting credentials
Since tempest change 290b3e138317062bd165df9eeaf17495135dfcfe
setUpClass (tempest.scenario.test_hugepages) fails
>>
File "tempest/scenario/test_hugepages.py", line 62, in setup_credentials
    credentials=cred_provider.get_configured_credentials(
AttributeError: 'module' object has no attribute 'get_configured_credentials'
>>

This commit should fix that.

Change-Id: I01f9b3d00e674a7cddd34ed85c3171e02eb90e97